In [2]:
import pandas as pd

text_data = {
    "Name": ["Arun", "Bala", "Chandru", "Divya", "Ezhil"],
    "Age": [20, 21, None, 22, 23],
    "Department": ["CSE", "IT", "CSE", None, "ECE"]
}

text_df = pd.DataFrame(text_data)

excel_data = {
    "Student": ["Ravi", "Priya", "Kumar", "Anu", "Vijay"],
    "Marks": [85, None, 78, 92, None],
    "Grade": ["A", "B", None, "A+", "B+"]
}

excel_df = pd.DataFrame(excel_data)

text_df.to_csv("Google_data_2b_c1.csv", index=False)
excel_df.to_excel("data_2c2.xlsx", sheet_name="Sheet1", index=False)

text_df = pd.read_csv("Google_data_2b_c1.csv")
excel_df = pd.read_excel("data_2c2.xlsx", sheet_name="Sheet1")

web_url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
web_df = pd.read_csv(web_url)

print("TEXT DATA")
display(text_df.head())

print("EXCEL DATA")
display(excel_df.head())

print("WEB DATA")
display(web_df.head())

text_df.ffill(inplace=True)
excel_df.bfill(inplace=True)
web_df.dropna(inplace=True)

text_df.to_csv("processed_text.csv", index=False)
excel_df.to_excel("processed_excel.xlsx", index=False)

print("PROCESSED TEXT DATA")
display(text_df)

print("PROCESSED EXCEL DATA")
display(excel_df)

print("PROCESSED WEB DATA")
display(web_df.head())

print("Data processing completed successfully!")

TEXT DATA

      Name   Age Department
0     Arun  20.0        CSE
1     Bala  21.0         IT
2  Chandru   NaN        CSE
3    Divya  22.0        NaN
4    Ezhil  23.0        ECE

EXCEL DATA

  Student  Marks Grade
0    Ravi   85.0     A
1   Priya    NaN     B
2   Kumar   78.0   NaN
3     Anu   92.0    A+
4   Vijay    NaN    B+

WEB DATA

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

PROCESSED TEXT DATA

      Name   Age Department
0     Arun  20.0        CSE
1     Bala  21.0         IT
2  Chandru  21.0        CSE
3    Divya  22.0        CSE
4    Ezhil  23.0        ECE

PROCESSED EXCEL DATA

  Student  Marks Grade
0    Ravi   85.0     A
1   Priya   78.0     B
2   Kumar   78.0    A+
3     Anu   92.0    A+
4   Vijay    NaN    B+

PROCESSED WEB DATA

    Country  Region
0   Algeria  AFRICA
1    Angola  AFRICA
2     Benin  AFRICA
3  Botswana  AFRICA
4   Burkina  AFRICA

Data processing completed successfully!